# Generated by Django 5.1 on 2026-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_giro_affari', models.CharField(choices=[('calato_molto', 'È calato molto'), ('calato_un_po', "È calato un po'"), ('uguale', 'È rimasto uguale'), ('migliorato', 'È migliorato'), ('molto_migliorato', 'È molto migliorato')], max_length=20)),
                ('q2_misura_dannosa', models.CharField(choices=[('zone_disco', 'Zone disco e parcheggi a pagamento in tutto il paese'), ('via_mazzini', 'Traffico limitato e rimozione parcheggi in via Mazzini'), ('permessi', 'Annullamento dei permessi di sosta per i residenti del centro'), ('tutte', 'Tutte e tre allo stesso modo'), ('nessuna', 'Nessuna in particolare')], max_length=20)),
                ('q3_impatto_parcheggi', models.CharField(choices=[('si_molti', 'Sì, molti evitano di venire in centro'), ('si_qualcuno', 'Sì, ma solo qualcuno'), ('no', 'No, non ho notato differenze'), ('non_so', 'Non so / difficile dirlo')], max_length=20)),
                ('q4_impatto_via_mazzini', models.CharField(choices=[('si_seri', 'Sì, problemi seri (carico/scarico difficile, clienti in meno)'), ('qualche', 'Qualche disagio, ma gestibile'), ('no', 'No, non mi ha riguardato'), ('non_app', 'Non applicabile alla mia attività')], max_length=20)),
                ('q5_frequenza_residenti', models.CharField(choices=[('meno', 'No, ne vedo meno'), ('uguale', 'Più o meno uguale'), ('non_so', 'Non saprei dirlo')], max_length=10)),
                ('q6_proposta', models.CharField(choices=[('parcheggi_gratuiti', 'Ripristinare i parcheggi gratuiti (anche solo in alcune fasce orarie)'), ('via_mazzini', 'Riaprire via Mazzini al traffico (almeno parzialmente)'), ('permessi_residenti', 'Reintrodurre i permessi per i residenti'), ('ora_gratuita', 'Prima ora di sosta gratuita ovunque'), ('altro', 'Altro (specificare)')], max_length=25)),
                ('q7_note', models.TextField(blank=True)),
                ('q8_tipo_attivita', models.CharField(choices=[('dettaglio', 'Negozio al dettaglio'), ('bar_ristorante', 'Bar / ristorante / pasticceria'), ('servizi', 'Servizi (studio professionale, parrucchiere, ecc.)'), ('altro', 'Altro')], max_length=20)),
                ('q9_posizione', models.CharField(choices=[('via_mazzini', 'Sì, in via Mazzini'), ('vicinanze', 'No, ma nelle immediate vicinanze'), ('altra_zona', "No, in un'altra zona del centro")], max_length=15)),
                ('q10_contatto_disponibile', models.CharField(choices=[('si', 'Sì, volentieri'), ('forse', 'Forse, dipende'), ('no', 'No, preferisco restare anonimo')], max_length=10)),
                ('q10_recapito', models.CharField(blank=True, max_length=200)),
                ('compilato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risposta',
                'verbose_name_plural': 'Risposte',
                'ordering': ['-compilato_il'],
            },
        ),
    ]
