# Generated by Django 5.1 on 2026-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risposta',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
